//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Geometry;

namespace RosMessageTypes.Ur5eMoveitActions
{
    [Serializable]
    public class ExecutePlanResultMsg : Message
    {
        public const string k_RosMessageName = "ur5e_moveit_actions/action/ExecutePlan_Result";
        public override string RosMessageName => k_RosMessageName;

        public bool success;
        public string message;
        public PoseStampedMsg final_pose;

        public ExecutePlanResultMsg()
        {
            this.success = false;
            this.message = "";
            this.final_pose = new PoseStampedMsg();
        }

        public ExecutePlanResultMsg(bool success, string message, PoseStampedMsg final_pose)
        {
            this.success = success;
            this.message = message;
            this.final_pose = final_pose;
        }

        public static ExecutePlanResultMsg Deserialize(MessageDeserializer deserializer) => new ExecutePlanResultMsg(deserializer);

        private ExecutePlanResultMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
            deserializer.Read(out this.message);
            this.final_pose = PoseStampedMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
            serializer.Write(this.message);
            serializer.Write(this.final_pose);
        }

        public override string ToString()
        {
            return "ExecutePlanResultMsg: " +
            "\nsuccess: " + success.ToString() +
            "\nmessage: " + message.ToString() +
            "\nfinal_pose: " + final_pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
