//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur5eMoveitActions
{
    [Serializable]
    public class ExecutePlanGoalMsg : Message
    {
        public const string k_RosMessageName = "ur5e_moveit_actions/action/ExecutePlan_Goal";
        public override string RosMessageName => k_RosMessageName;

        public string plan_id;

        public ExecutePlanGoalMsg()
        {
            this.plan_id = "";
        }

        public ExecutePlanGoalMsg(string plan_id)
        {
            this.plan_id = plan_id;
        }

        public static ExecutePlanGoalMsg Deserialize(MessageDeserializer deserializer) => new ExecutePlanGoalMsg(deserializer);

        private ExecutePlanGoalMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.plan_id);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.plan_id);
        }

        public override string ToString()
        {
            return "ExecutePlanGoalMsg: \nplan_id: " + plan_id.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
