//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Geometry;

namespace RosMessageTypes.Ur5eMoveitActions
{
    [Serializable]
    public class PlanToPoseGoalMsg : Message
    {
        public const string k_RosMessageName = "ur5e_moveit_actions/action/PlanToPose_Goal";
        public override string RosMessageName => k_RosMessageName;

        public PoseStampedMsg target_pose;
        public double planning_time;
        public double velocity_scaling;
        public double acceleration_scaling;
        public string planning_id;

        public PlanToPoseGoalMsg()
        {
            this.target_pose = new PoseStampedMsg();
            this.planning_time = 0.0;
            this.velocity_scaling = 0.0;
            this.acceleration_scaling = 0.0;
            this.planning_id = "";
        }

        public PlanToPoseGoalMsg(PoseStampedMsg target_pose, double planning_time, double velocity_scaling, double acceleration_scaling, string planning_id)
        {
            this.target_pose = target_pose;
            this.planning_time = planning_time;
            this.velocity_scaling = velocity_scaling;
            this.acceleration_scaling = acceleration_scaling;
            this.planning_id = planning_id;
        }

        public static PlanToPoseGoalMsg Deserialize(MessageDeserializer deserializer) => new PlanToPoseGoalMsg(deserializer);

        private PlanToPoseGoalMsg(MessageDeserializer deserializer)
        {
            this.target_pose = PoseStampedMsg.Deserialize(deserializer);
            deserializer.Read(out this.planning_time);
            deserializer.Read(out this.velocity_scaling);
            deserializer.Read(out this.acceleration_scaling);
            deserializer.Read(out this.planning_id);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.target_pose);
            serializer.Write(this.planning_time);
            serializer.Write(this.velocity_scaling);
            serializer.Write(this.acceleration_scaling);
            serializer.Write(this.planning_id);
        }

        public override string ToString()
        {
            return "PlanToPoseGoalMsg: " +
            "\ntarget_pose: " + target_pose.ToString() +
            "\nplanning_time: " + planning_time.ToString() +
            "\nvelocity_scaling: " + velocity_scaling.ToString() +
            "\nacceleration_scaling: " + acceleration_scaling.ToString() +
            "\nplanning_id: " + planning_id.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}