//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Geometry;

namespace RosMessageTypes.Ur5eMoveitActions
{
    [Serializable]
    public class PlanToPoseResultMsg : Message
    {
        public const string k_RosMessageName = "ur5e_moveit_actions/action/PlanToPose_Result";
        public override string RosMessageName => k_RosMessageName;

        public bool success;
        public string message;
        public string plan_id;
        public PointMsg[] tcp_waypoints;
        public double plan_duration;

        public PlanToPoseResultMsg()
        {
            this.success = false;
            this.message = "";
            this.plan_id = "";
            this.tcp_waypoints = new PointMsg[0];
            this.plan_duration = 0.0;
        }

        public PlanToPoseResultMsg(bool success, string message, string plan_id, PointMsg[] tcp_waypoints, double plan_duration)
        {
            this.success = success;
            this.message = message;
            this.plan_id = plan_id;
            this.tcp_waypoints = tcp_waypoints;
            this.plan_duration = plan_duration;
        }

        public static PlanToPoseResultMsg Deserialize(MessageDeserializer deserializer) => new PlanToPoseResultMsg(deserializer);

        private PlanToPoseResultMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
            deserializer.Read(out this.message);
            deserializer.Read(out this.plan_id);
            deserializer.Read(out this.tcp_waypoints, PointMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.plan_duration);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
            serializer.Write(this.message);
            serializer.Write(this.plan_id);
            serializer.WriteLength(this.tcp_waypoints);
            serializer.Write(this.tcp_waypoints);
            serializer.Write(this.plan_duration);
        }

        public override string ToString()
        {
            return "PlanToPoseResultMsg: " +
            "\nsuccess: " + success.ToString() +
            "\nmessage: " + message.ToString() +
            "\nplan_id: " + plan_id.ToString() +
            "\ntcp_waypoints: " + System.String.Join(", ", tcp_waypoints.ToList()) +
            "\nplan_duration: " + plan_duration.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
